# Staging environment configuration
project_id = "subkcevxjivxiiksnytj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.seed]
enabled = true
sql_paths = ['./seed.staging.sql']

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "https://subkcevxjivxiiksnytj.supabase.co"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://staging.example.com"
additional_redirect_urls = ["https://staging.example.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = true
port = 54327
backend = "postgres"